name: "Deploy on dokku from git source"
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Ref to deploy
        type: string
        required: true
      deploy-to:
        description: Environment to deploy
        type: choice
        required: true
        options:
          - prod
jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yaml
    secrets: inherit
    with:
      ref: "${{ inputs.ref }}"
      deploy-to: "${{ inputs.deploy-to }}"
      deploy-method: git
